.PHONY: clean All

All:
	@echo "----------Building project:[ ejercicio10 - Release ]----------"
	@cd "ejercicio10" && "$(MAKE)" -f  "ejercicio10.mk"
clean:
	@echo "----------Cleaning project:[ ejercicio10 - Release ]----------"
	@cd "ejercicio10" && "$(MAKE)" -f  "ejercicio10.mk" clean
