.PHONY: clean All

All:
	@echo "----------Building project:[ pruebachar - Debug ]----------"
	@cd "pruebachar" && "$(MAKE)" -f  "pruebachar.mk"
clean:
	@echo "----------Cleaning project:[ pruebachar - Debug ]----------"
	@cd "pruebachar" && "$(MAKE)" -f  "pruebachar.mk" clean
